name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  ci:
    name: Setup application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 'v9.15.4'

      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run formatters
        run: |
          pnpm lint
          pnpm format

      - name: Build application
        run: pnpm build

      - name: Generate semantic release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
