name: Setup

on:
  workflow_call:

jobs:
  setup-application:
    name: Setup application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run formatters
        run: |
          pnpm lint
          pnpm format
